# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowIcon(QtGui.QIcon("icon.jpg"))
        MainWindow.resize(888, 608)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_account = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tab_account.setGeometry(QtCore.QRect(0, 10, 881, 581))
        self.tab_account.setObjectName("tab_account")
        self.Account = QtWidgets.QWidget()
        self.Account.setObjectName("Account")
        self.list_account_ac = QtWidgets.QListWidget(parent=self.Account)
        self.list_account_ac.setGeometry(QtCore.QRect(670, 50, 191, 431))
        self.list_account_ac.setObjectName("list_account_ac")
        self.add_account = QtWidgets.QPushButton(parent=self.Account)
        self.add_account.setGeometry(QtCore.QRect(200, 20, 101, 31))
        self.add_account.setObjectName("add_account")
        self.account_input_add = QtWidgets.QLineEdit(parent=self.Account)
        self.account_input_add.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.account_input_add.setObjectName("account_input_add")
        self.remove_account_input = QtWidgets.QLineEdit(parent=self.Account)
        self.remove_account_input.setGeometry(QtCore.QRect(10, 70, 181, 31))
        self.remove_account_input.setObjectName("remove_account_input")
        self.remove_account_bot = QtWidgets.QPushButton(parent=self.Account)
        self.remove_account_bot.setGeometry(QtCore.QRect(200, 70, 101, 31))
        self.remove_account_bot.setObjectName("remove_account_bot")
        self.help_account_add = QtWidgets.QTextBrowser(parent=self.Account)
        self.help_account_add.setGeometry(QtCore.QRect(310, 20, 341, 31))
        self.help_account_add.setObjectName("help_account_add")
        self.help_remove_account = QtWidgets.QTextBrowser(parent=self.Account)
        self.help_remove_account.setGeometry(QtCore.QRect(310, 70, 341, 41))
        self.help_remove_account.setObjectName("help_remove_account")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.Account)
        self.textBrowser_2.setGeometry(QtCore.QRect(710, 20, 111, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.Account)
        self.lcdNumber.setGeometry(QtCore.QRect(690, 490, 151, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        self.update_number_bot = QtWidgets.QPushButton(parent=self.Account)
        self.update_number_bot.setGeometry(QtCore.QRect(570, 500, 111, 41))
        self.update_number_bot.setObjectName("update_number_bot")
        self.tab_account.addTab(self.Account, "")
        self.Extract = QtWidgets.QWidget()
        self.Extract.setObjectName("Extract")
        self.group_extracct_input = QtWidgets.QLineEdit(parent=self.Extract)
        self.group_extracct_input.setGeometry(QtCore.QRect(20, 20, 301, 31))
        self.group_extracct_input.setText("")
        self.group_extracct_input.setObjectName("group_extracct_input")
        self.extract_bot = QtWidgets.QPushButton(parent=self.Extract)
        self.extract_bot.setGeometry(QtCore.QRect(340, 20, 131, 31))
        self.extract_bot.setObjectName("extract_bot")
        self.lcdNumber_member_extract = QtWidgets.QLCDNumber(parent=self.Extract)
        self.lcdNumber_member_extract.setGeometry(QtCore.QRect(500, 60, 161, 81))
        self.lcdNumber_member_extract.setObjectName("lcdNumber_member_extract")
        self.list_ex = QtWidgets.QListWidget(parent=self.Extract)
        self.list_ex.setGeometry(QtCore.QRect(20, 120, 301, 431))
        self.list_ex.setObjectName("list_ex")
        self.stop_extract = QtWidgets.QPushButton(parent=self.Extract)
        self.stop_extract.setGeometry(QtCore.QRect(510, 20, 131, 31))
        self.stop_extract.setObjectName("stop_extract")
        self.status_extract = QtWidgets.QTextBrowser(parent=self.Extract)
        self.status_extract.setGeometry(QtCore.QRect(330, 60, 161, 31))
        self.status_extract.setObjectName("status_extract")
        self.list_group_rem = QtWidgets.QComboBox(parent=self.Extract)
        self.list_group_rem.setGeometry(QtCore.QRect(340, 160, 231, 31))
        self.list_group_rem.setObjectName("list_group_rem")
        self.rem_extract_bot = QtWidgets.QPushButton(parent=self.Extract)
        self.rem_extract_bot.setGeometry(QtCore.QRect(390, 200, 131, 51))
        self.rem_extract_bot.setObjectName("rem_extract_bot")
        self.help_ex_link = QtWidgets.QTextBrowser(parent=self.Extract)
        self.help_ex_link.setGeometry(QtCore.QRect(20, 60, 301, 41))
        self.help_ex_link.setObjectName("help_ex_link")
        self.log_extract = QtWidgets.QPlainTextEdit(parent=self.Extract)
        self.log_extract.setGeometry(QtCore.QRect(340, 330, 521, 211))
        self.log_extract.setObjectName("log_extract")
        self.label = QtWidgets.QLabel(parent=self.Extract)
        self.label.setGeometry(QtCore.QRect(670, 10, 191, 51))
        self.label.setObjectName("label")
        self.tab_account.addTab(self.Extract, "")
        self.Extract_message = QtWidgets.QWidget()
        self.Extract_message.setObjectName("Extract_message")
        self.log_extract_2 = QtWidgets.QPlainTextEdit(parent=self.Extract_message)
        self.log_extract_2.setGeometry(QtCore.QRect(340, 330, 521, 211))
        self.log_extract_2.setObjectName("log_extract_2")
        self.lcdNumber_member_extract_2 = QtWidgets.QLCDNumber(parent=self.Extract_message)
        self.lcdNumber_member_extract_2.setGeometry(QtCore.QRect(500, 60, 161, 81))
        self.lcdNumber_member_extract_2.setObjectName("lcdNumber_member_extract_2")
        self.help_ex_link_2 = QtWidgets.QTextBrowser(parent=self.Extract_message)
        self.help_ex_link_2.setGeometry(QtCore.QRect(20, 60, 301, 41))
        self.help_ex_link_2.setObjectName("help_ex_link_2")
        self.list_group_rem_2 = QtWidgets.QComboBox(parent=self.Extract_message)
        self.list_group_rem_2.setGeometry(QtCore.QRect(340, 160, 231, 31))
        self.list_group_rem_2.setObjectName("list_group_rem_2")
        self.extract_bot_2 = QtWidgets.QPushButton(parent=self.Extract_message)
        self.extract_bot_2.setGeometry(QtCore.QRect(340, 20, 131, 31))
        self.extract_bot_2.setObjectName("extract_bot_2")
        self.status_extract_2 = QtWidgets.QTextBrowser(parent=self.Extract_message)
        self.status_extract_2.setGeometry(QtCore.QRect(330, 60, 161, 31))
        self.status_extract_2.setObjectName("status_extract_2")
        self.group_extracct_input_2 = QtWidgets.QLineEdit(parent=self.Extract_message)
        self.group_extracct_input_2.setGeometry(QtCore.QRect(20, 20, 301, 31))
        self.group_extracct_input_2.setText("")
        self.group_extracct_input_2.setObjectName("group_extracct_input_2")
        self.list_ex_2 = QtWidgets.QListWidget(parent=self.Extract_message)
        self.list_ex_2.setGeometry(QtCore.QRect(20, 120, 301, 431))
        self.list_ex_2.setObjectName("list_ex_2")
        self.stop_extract_2 = QtWidgets.QPushButton(parent=self.Extract_message)
        self.stop_extract_2.setGeometry(QtCore.QRect(510, 20, 131, 31))
        self.stop_extract_2.setObjectName("stop_extract_2")
        self.rem_extract_bot_2 = QtWidgets.QPushButton(parent=self.Extract_message)
        self.rem_extract_bot_2.setGeometry(QtCore.QRect(390, 200, 131, 51))
        self.rem_extract_bot_2.setObjectName("rem_extract_bot_2")
        self.label_2 = QtWidgets.QLabel(parent=self.Extract_message)
        self.label_2.setGeometry(QtCore.QRect(650, 10, 221, 51))
        self.label_2.setObjectName("label_2")
        self.tab_account.addTab(self.Extract_message, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_account.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Telegram Members Extractor By https://erfan4lx.com"))
        self.add_account.setText(_translate("MainWindow", "Add account"))
        self.account_input_add.setText(_translate("MainWindow", "+123456789"))
        self.remove_account_input.setText(_translate("MainWindow", "+123456789"))
        self.remove_account_bot.setText(_translate("MainWindow", "Remove account"))
        self.help_account_add.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">This section is for adding an account.</span></p></body></html>"))
        self.help_remove_account.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">This section is for deleting an existing account in the program.</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">List Accounts</span></p></body></html>"))
        self.update_number_bot.setText(_translate("MainWindow", "Update Number"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.Account), _translate("MainWindow", "Accounts Login"))
        self.extract_bot.setText(_translate("MainWindow", "Extracting members"))
        self.stop_extract.setText(_translate("MainWindow", "Stop Extract"))
        self.status_extract.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Status : Disactive</span></p></body></html>"))
        self.rem_extract_bot.setText(_translate("MainWindow", "Remove Gap Extract"))
        self.help_ex_link.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">link : @group | t.me/+Smxcjsiw28cx</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Members List Extraction</span></p></body></html>"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.Extract), _translate("MainWindow", "Extract By Members List"))
        self.help_ex_link_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">link : @group | t.me/+Smxcjsiw28cx</span></p></body></html>"))
        self.extract_bot_2.setText(_translate("MainWindow", "Extracting members"))
        self.status_extract_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Status : Disactive</span></p></body></html>"))
        self.stop_extract_2.setText(_translate("MainWindow", "Stop Extract"))
        self.rem_extract_bot_2.setText(_translate("MainWindow", "Remove Gap Extract"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Group Messages Extraction</span></p></body></html>"))
        self.tab_account.setTabText(self.tab_account.indexOf(self.Extract_message), _translate("MainWindow", "Extract By Group Chat"))
